"""add read_stat and daily_read_stat

Revision ID: 132358c2be1a
Revises: 891d8dc0c69a
Create Date: 2026-06-30 11:04:01.626884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132358c2be1a'
down_revision = '891d8dc0c69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_read_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_read_time', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_table('read_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_read_time', sa.Integer(), nullable=True),
    sa.Column('read_days', sa.Integer(), nullable=True),
    sa.Column('day_avg_read_time', sa.Integer(), nullable=True),
    sa.Column('compare', sa.Float(), nullable=True),
    sa.Column('read_longest', sa.JSON(), nullable=True),
    sa.Column('read_stat', sa.JSON(), nullable=True),
    sa.Column('prefer_category', sa.JSON(), nullable=True),
    sa.Column('prefer_time_word', sa.String(length=100), nullable=True),
    sa.Column('prefer_author', sa.JSON(), nullable=True),
    sa.Column('prefer_time', sa.JSON(), nullable=True),
    sa.Column('read_rate', sa.Float(), nullable=True),
    sa.Column('wr_read_time', sa.Integer(), nullable=True),
    sa.Column('wr_listen_time', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode', 'period_start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_stat')
    op.drop_table('daily_read_stat')
    # ### end Alembic commands ###
