"""add display_size to note_image

Revision ID: 22ef1b2cb267
Revises: e709fcd61ea3
Create Date: 2026-06-30 09:56:00.765416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef1b2cb267'
down_revision = 'e709fcd61ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_size', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_images', schema=None) as batch_op:
        batch_op.drop_column('display_size')

    # ### end Alembic commands ###
