"""用户 API Key — users 表添加 weread_api_key 字段

Revision ID: 27f87824869d
Revises: 0229153af526
Create Date: 2026-06-30 16:13:42.985498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f87824869d'
down_revision = '0229153af526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weread_api_key', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weread_api_key')

    # ### end Alembic commands ###
