"""add_highlight_id_to_notes

Revision ID: 3bbb211a2dd1
Revises: 8fdfa760bb78
Create Date: 2026-07-01 19:46:26.885573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbb211a2dd1'
down_revision = '8fdfa760bb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlight_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'highlights', ['highlight_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('highlight_id')

    # ### end Alembic commands ###
