"""添加阅读进度 — books 表添加 progress 字段(0-100)

Revision ID: 61af57676bcc
Revises: c12412055e62
Create Date: 2026-07-01 19:10:43.836882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61af57676bcc'
down_revision = 'c12412055e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
