"""add user_id to book, highlight, and shelf_synced to user

Revision ID: 863dbd349b9b
Revises: 27f87824869d
Create Date: 2026-06-30 16:24:42.276743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863dbd349b9b'
down_revision = '27f87824869d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_index(batch_op.f('isbn'))
        batch_op.create_index(batch_op.f('ix_books_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_highlights_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_synced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('shelf_synced')

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_highlights_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_books_user_id'))
        batch_op.create_index(batch_op.f('isbn'), ['isbn'], unique=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
