"""笔记图片宽度 — 将 display_size 改为 display_width

Revision ID: 891d8dc0c69a
Revises: 22ef1b2cb267
Create Date: 2026-06-30 10:02:32.133206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '891d8dc0c69a'
down_revision = '22ef1b2cb267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_width', sa.Integer(), nullable=True))
        batch_op.drop_column('display_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_size', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.drop_column('display_width')

    # ### end Alembic commands ###
