"""性能优化 — 补充数据库索引和外键级联删除

Revision ID: 8cefe4d3087d
Revises: ebfa50748674
Create Date: 2026-07-01 18:50:01.602853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cefe4d3087d'
down_revision = 'ebfa50748674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_chat_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_chat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_weread_book_id'), ['weread_book_id'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlights_book_id'), ['book_id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_book_id'))

    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlights_book_id'))

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_user_id'))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_weread_book_id'))
        batch_op.drop_index(batch_op.f('ix_books_status'))
        batch_op.drop_index(batch_op.f('ix_books_created_at'))
        batch_op.drop_index(batch_op.f('ix_books_category_id'))

    with op.batch_alter_table('book_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_book_chat_book_id'))

    # ### end Alembic commands ###
