"""添加最近阅读时间 — books 表添加 last_read_at 字段

Revision ID: 8fdfa760bb78
Revises: 61af57676bcc
Create Date: 2026-07-01 19:27:42.100491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdfa760bb78'
down_revision = '61af57676bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('last_read_at')

    # ### end Alembic commands ###
