"""书架软删除 — books 表添加 shelved 字段，下架书不物理删除

Revision ID: c12412055e62
Revises: 8cefe4d3087d
Create Date: 2026-07-01 18:54:31.917791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12412055e62'
down_revision = '8cefe4d3087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelved', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_books_shelved'), ['shelved'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_shelved'))
        batch_op.drop_column('shelved')

    # ### end Alembic commands ###
