"""添加划线笔记表 — highlights 表，支持微信读书划线导入

Revision ID: c5004a3ee73c
Revises: 6e1b3fa070b6
Create Date: 2026-06-29 15:22:40.078480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5004a3ee73c'
down_revision = '6e1b3fa070b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('weread_bookmark_id', sa.String(length=100), nullable=False),
    sa.Column('chapter_uid', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.String(length=200), nullable=True),
    sa.Column('mark_text', sa.Text(), nullable=False),
    sa.Column('range', sa.String(length=100), nullable=True),
    sa.Column('color_style', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlights')
    # ### end Alembic commands ###
