"""add thought model

Revision ID: e06ab06efc8c
Revises: 3bbb211a2dd1
Create Date: 2026-07-20 17:19:52.238184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e06ab06efc8c'
down_revision = '3bbb211a2dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thoughts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('weread_review_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('thought_type', sa.String(length=20), nullable=True),
    sa.Column('chapter_name', sa.String(length=200), nullable=True),
    sa.Column('is_finish', sa.Boolean(), nullable=True),
    sa.Column('ref_range', sa.String(length=100), nullable=True),
    sa.Column('ref_abstract', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weread_review_id')
    )
    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thoughts_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thoughts_highlight_id'), ['highlight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thoughts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('weread_api_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('weread_api_key',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)

    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thoughts_user_id'))
        batch_op.drop_index(batch_op.f('ix_thoughts_highlight_id'))
        batch_op.drop_index(batch_op.f('ix_thoughts_book_id'))

    op.drop_table('thoughts')
    # ### end Alembic commands ###
