"""add thinker theme

Revision ID: e1ee992eb795
Revises: e48938ba86dd
Create Date: 2026-07-01 09:31:31.119839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ee992eb795'
down_revision = 'e48938ba86dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinker', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
