"""哲学家开场白 — thinker 表添加 opening_line 字段

Revision ID: e48938ba86dd
Revises: e06662e5dc45
Create Date: 2026-06-30 20:40:23.176493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48938ba86dd'
down_revision = 'e06662e5dc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_line', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinker', schema=None) as batch_op:
        batch_op.drop_column('opening_line')

    # ### end Alembic commands ###
