"""添加本地查看时间 — books 表添加 last_viewed_at 字段

Revision ID: fa7025faea0e
Revises: 6a0e3ad145dc
Create Date: 2026-06-29 20:25:44.317558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7025faea0e'
down_revision = '6a0e3ad145dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_viewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('last_viewed_at')

    # ### end Alembic commands ###
